content/index.rst
=> edit who is this for? to remove focus from the CR lessons

content/hackmd.rst, content/index.rst, content/teaching-online.md, content/team-teaching.rst
- Begin adding pages and linking to the manuals
- Review: general check or automerge and iterate
=> Increment on content

content/about-coderefinery.md
=> info about Carpentries membership was outdated

content/guide.rst, content/quick-reference.rst
- Not material for this lesson but describe what they would be used for
=> guide, quick-reference: Add descriptive to empty pages

content/instructor-tech-setup.rst
- Screenshots make it more clear
=> content/instructor-tech-setup: Add screenshots

content/video-recording.rst
- It was a bit awkward and hard to understand
- This might fix #8
- Review: check if the new wording makes sense
=> content/video-recording: Rephrase the privacy+disclaimer sentence

content/index.rst
- Like before the rearrangement for carpentrycon
- Review: automerge
=> content/index: Reorganize to the four categories

content/CodeRefinery_intro.md, content/index.md, content/onboarding.md, content/overview.md
@rkdarst @dhanyapushpadas @stepas-toliautas 
What do you think about the structure? 
Any ideas for fun exercises/discussions?
Related #73 ; 
regarding #87  and #86
=> A first draft for overview and onboarding episode

content/lesson-template.md
Co-authored-by @bast 
Co-authored-by @rkdarst
Relates  to #74 #85
=> First lesson template draft based on RD and RB comments

content/lesson-development.md
=> Exercises and learner personas

content/index.md, content/lessons-with-git.md
- Based on discussion today
- It's not only about git but it's a short and well-known concept.
- Review: automerge (making this just to have future PR clean)
=> Rename lesson-template -> lessons-with-git

content/lessons-with-git.md
- General update based on what we have discussed today.
- Not final, but ready for some comments and more iteration.
- Review: automerge
=> content/lessons-with-git: General update

content/guide.md
@rkdarst could you fill in day 4 topics as you plan to do them?
=> Add approximate timing for session 3 + 4 

README.md
Review: All needed info provided?
resolves #129
=> Fill README with useful information

content/sound.md
- The exercises, around which other things can be designed (and can be
discussed)
- Review: automerge
=> content/sound: Initial sound work (sections and exercises only)

content/index.md, content/notes-archive.md
- ok? 
- need more formatting?
- should we remove the "answers" on feedback?
=> Add Session 1 notes

content/overview.md
- Forgotten anything?
Closes #87
=> Add points from meeting discussion to overview page

content/collaborative-notes.md
Here is the updates to the collaborative document. Please review the exercise and see more questions can be added.
=> Update collaborative doc

content/notes-archive.md
- all names/ other identifying info removed? 
- any more answers to add?
=> Add Day 2 Notes

content/teaching-philosophies.md
Maybe there can be more personal experiences added, but we have enough for a good discussion in the breakout rooms.
=> Update teaching philosophies

content/co-teaching.md
It would be great to expand on the last hint, why and how not every learner might like the team-taught lessons.
=> Co-teaching episode update

content/notes-archive.md
Could you check that all names have been removed and the header levels are consitent?
Thank you!
=> Add Day 3 notes
